name: Nightly build

on:
  schedule:
    - cron: 16 2 * * *
  workflow_dispatch: null

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
    if: github.repository_owner == makuser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Install
        run: npm ci

      - name: Generate OpenAPI Docs
        run: npm run build_openapi_schema
      - name: Build Valetudo frontend
        run: npm run build --workspace=frontend

      - name: Build Valetudo armv7
        run: npm run build_armv7 --workspace=backend
      - name: Build Valetudo armv7 lowmem
        run: npm run build_armv7_lowmem --workspace=backend
      - name: Build Valetudo aarch64
        run: npm run build_aarch64 --workspace=backend

      - name: UPX-compress valetudo binaries
        run: npm run upx

      - name: Generate changelog
        run: npm run generate_nightly_changelog

      - name: Build manifest
        run: npm run build_release_manifest nightly

      - name: Release Valetudo
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            build/valetudo-armv7
            build/valetudo-armv7.upx
            build/valetudo-aarch64
            build/valetudo-aarch64.upx
            build/valetudo-armv7-lowmem
            build/valetudo-armv7-lowmem.upx
            build/valetudo_release_manifest.json
            build/valetudo.openapi.schema.json